homeassistant:
  name: !secret HOME_NAME
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  elevation: !secret HOME_ELAVATION
  unit_system: metric
  time_zone: !secret HOME_TIME_ZONE
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
   - type: trusted_networks
  whitelist_external_dirs:
    - '/config'
  

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Discover some devices automatically
discovery:
  ignore:
    - xiaomi_gw
  #   - philips_hue
  #   - ikea_tradfri
  #   - sonos

# Enables the auth component
auth:

# ########################################
# ###                UI                ###
# ########################################

# Configure Home Assistant to use HTTPS
http:
  base_url: !secret HTTP_URL
  api_password: !secret HTTP_PASSWORD
  ssl_certificate: !secret SSL_CERTIFICATE
  ssl_key: !secret SSL_KEY
  trusted_networks:
    - !secret HTTP_TRUSTED_IP_INTERNAL
    - !secret HTTP_TRUSTED_IP_EXTERNAL
  login_attempts_threshold: 3

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'

# Enables a map showing the location of tracked devices
map:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables the Hassio configuration
hassio:

# Enables Home Assistant Cloud
# cloud:

# Enables configuration UI
config:

# ########################################
# ###              LOGGING             ###
# ########################################

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
