homeassistant:

# hue:
#   bridges:
#     - host: !secret HUE_IP_ADDRESS

group:
  hue_devices:
    name: Hue Devices
    entities:
      - group.hue_kinderkamer_elise
      - group.hue_babykamer_luuk
      - group.hue_slaapkamer
      - group.hue_gang_boven
      - group.hue_gang_beneden
      - group.hue_washok
      - group.hue_badkamer
      - group.hue_woonkamer
      - group.hue_eetkamer
  hue_kinderkamer_elise:
    name: Hue Devices - Kamer Elise
    entities:
      - light.kinderkamer
      - light.kinderkamer_1
      - light.kinderkamer_2
      - light.kinderkamer_3
  hue_babykamer_luuk:
    name: Hue Devices - Kamer Luuk
    entities:
      - light.babykamer
      - light.babykamer_1
      - light.babykamer_2
      - light.babykamer_3
  hue_babykamer_slaapkamer:
    name: Hue Devices - Slaapkamer
    entities:
      - light.slaapkamer
      - light.slaapkamer_1
      - light.slaapkamer_2
      - light.slaapkamer_3
  hue_gang_boven:
    name: Hue Devices - Gang boven
    entities:
      - light.gang_boven
      - light.gang_boven_1
  hue_gang_beneden:
    name: Hue Devices - Gang beneden
    entities:
      - light.gang_beneden
      - light.gang_beneden_1
  hue_washok:
    name: Hue Devices - Washok
    entities:
      - light.washok
      - light.washok_1
  hue_badkamer:
    name: Hue Devices - Badkamer
    entities:
      - light.badkamer
      - light.badkamer_1
  hue_woonkamer:
    name: Hue Devices - Woonkamer
    entities:
      - light.woonkamer
      - light.woonkamer_1
      - light.woonkamer_2
      - light.woonkamer_3
  hue_eetkamer:
    name: Hue Devices - Eetkamer
    entities:
      - light.eetkamer
      - light.eetkamer_1
      - light.eetkamer_2