homeassistant:
  customize_glob:
    sensor.plant*:
      hidden: true

sensor:
  platform: miflora
  name: 'Plant'
  mac: 'C4:7C:8D:65:E7:37'
  force_update: true
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

plant:
  plant:
    sensors:
      moisture: sensor.plant_moisture
      battery: sensor.plant_battery
      temperature: sensor.plant_temperature
      conductivity: sensor.plant_conductivity
      brightness: sensor.plant_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_battery: 10
    min_conductivity: 500
    max_conductivity: 3000
    min_temperature: 15
    max_temperature: 30