homeassistant:

# tradfri:
#   host: TRADFRI_IP_ADDRESS

group:
  tradfri_devices:
    name: Trådfri Devices
    entities:
      - group.tradfri_berging
      - group.tradfri_garderobe
      - group.tradfri_kantoor
      - group.tradfri_wc_beneden
      - sensor.tradfri_remote_control
  tradfri_berging:
    name: Trådfri Devices - Berging
    entities:
      - light.berging
      - light.berging_1
      - light.berging_2
      - light.berging_3
  tradfri_garderobe:
    name: Trådfri Devices - Garderobe
    entities:
      - light.garderobe
      - light.garderobe_1
      - light.garderobe_2
      - light.garderobe_3
  tradfri_kantoor:
    name: Trådfri Devices - Kantoor
    entities:
      - light.kantoor
      - light.kantoor_1
      - light.kantoor_2
      - light.kantoor_3
  tradfri_wc_beneden:
    name: Trådfri Devices - Wc beneden
    entities:
      - light.wc_beneden
      - light.wc_beneden_1